### ISSUE TITLE
ATCConsole.println don't print messages to console 

### ISSUE THREAD

**Issue by gabrielsr** [lesunb/RGMToPRISM#7]
When generating a model should be printed in console, for info purpose things such as:

Generating DTMC model for: Actor 1
DTMC model created in 77082ms.

But ATCConsole.println don't print anything. 

Tested on Luna 4.4. Running the in debug mode.

**Comment by danilomendonca** [comment]
I'm back!

Esse log sai no workspace de teste e não no workspace de desenvolvimento. Você olhou no console certo?

**Comment by gabrielsr** [comment]
Opa! Provavelmente não. Valeu!
